apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cheese-quizz
    version: v1
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: cheese-quizz-question
    app.kubernetes.io/part-of: cheese-quizz-app
    app.openshift.io/runtime: quarkus
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/lbroudoux/cheese-quizz'
  name: cheese-quizz-question-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese-quizz-question
      version: v1
  template:
    metadata:
      labels:
        app: cheese-quizz-question
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: quay.io/lbroudoux/cheese-quizz-question:latest
        imagePullPolicy: Always
        name: quizz-question
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
        volumeMounts:                                               
        - name: quizz-question-config
          mountPath: /work/config
        securityContext:
          privileged: false
      volumes:                                                      
      - name: quizz-question-config
        configMap:                                                
          name: cheese-quizz-question-v1-config
